declare const _default: import("vue").DefineComponent<{}, {
    $emit: (event: "toggleResults" | "inputFocused" | "searchSubmit", ...args: any[]) => void;
    isActive: boolean;
    autoHide: boolean;
    showSubtitles: boolean;
    isFullScreen: boolean;
    isRaw: boolean;
    isAutoPilotLoading: boolean;
    isIframe: boolean;
    toggleShareModal: Function;
    searchContent: string;
    searchLoading: boolean;
    searchInputPlaceholder: string;
    wordsLoading: boolean;
    showSearchResults: boolean;
    onSearchChange: Function;
    searchSuggestions: unknown[];
    searchResults: Record<string, any>;
    updateParentIsFocused: Function;
    highlights: unknown[];
    playPaused: Function;
    subtitles: string;
    videoTitle: string;
    subtitleBacked: boolean;
    toggleSubtiles: Function;
    isSummaryVisible: boolean;
    isLight: boolean;
    $props: {
        readonly isActive?: boolean | undefined;
        readonly autoHide?: boolean | undefined;
        readonly showSubtitles?: boolean | undefined;
        readonly isFullScreen?: boolean | undefined;
        readonly isRaw?: boolean | undefined;
        readonly isAutoPilotLoading?: boolean | undefined;
        readonly isIframe?: boolean | undefined;
        readonly toggleShareModal?: Function | undefined;
        readonly searchContent?: string | undefined;
        readonly searchLoading?: boolean | undefined;
        readonly searchInputPlaceholder?: string | undefined;
        readonly wordsLoading?: boolean | undefined;
        readonly showSearchResults?: boolean | undefined;
        readonly onSearchChange?: Function | undefined;
        readonly searchSuggestions?: unknown[] | undefined;
        readonly searchResults?: Record<string, any> | undefined;
        readonly updateParentIsFocused?: Function | undefined;
        readonly highlights?: unknown[] | undefined;
        readonly playPaused?: Function | undefined;
        readonly subtitles?: string | undefined;
        readonly videoTitle?: string | undefined;
        readonly subtitleBacked?: boolean | undefined;
        readonly toggleSubtiles?: Function | undefined;
        readonly isSummaryVisible?: boolean | undefined;
        readonly isLight?: boolean | undefined;
    };
}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<import("vue").ExtractPropTypes<{}>>, {}, {}>;
export default _default;
